Mattshark89/OpenFlight-VRC

- Assets/OpenFlight-VRC/data.json
* Nico https://booth.pm/en/items/3940118
* Harmir https://teaf.booth.pm/items/2890693
* Nenon https://aokuro.booth.pm/items/1551159
* Nunon https://aokuro.booth.pm/items/2006880
* Milnenu https://aokuro.booth.pm/items/2591645
* Milnunu https://aokuro.booth.pm/items/3173822
* Milnonu https://aokuro.booth.pm/items/3447637
* Sufosni https://aokuro.booth.pm/items/4363768
> Add aokuro harpies and two other birds

- Assets/OpenFlight-VRC/data.json
* 2 or 4 Eyed Owl https://spacebirb.gumroad.com/l/owlfriend
* Kuda's Avians https://kudalyn.gumroad.com/l/eltGi
* Avigen https://mikedabird.itch.io/avigen
> Add three more flying avatars

- Assets/OpenFlight-VRC/data.json
* Beriul https://am23ti.booth.pm/items/4321056
* Nico the Floof https://alexthecat.gumroad.com/l/nicothefloof
> Add Beriul, Nico the Floof

- Assets/OpenFlight-VRC/data.json
Avali Army: https://discord.com/channels/530351426833088512/1060234969517129778/1089970731770728478
Bump JSON version to 1.0.0 for release versioning
> Added Petrenkavali (Petvali)

- Assets/OpenFlight-VRC/data.json
https://spaghet-vr.gumroad.com/l/raptor
> Added VRaptor

- Packages/com.mattshark.openflight/Runtime/data.json
https://avislime.gumroad.com/l/kyliin
> Add Kyliin Redux

- Packages/com.mattshark.openflight/Runtime/data.json
Added v2 hashes for the Bitty Bat, Fowl, and Yang Firebird
> Added v2 hashes

- Packages/com.mattshark.openflight/Runtime/data.json
Added the wyvern variant of the [Maximus Draconis](https://dragonskyrunner.gumroad.com/l/MaximusDraconis)
> add the Maximus Draconis Wyvern

- README.md
- docs/README.md
Updated the world over the weekend with some generated mountain topology. OpenFlight officially a better workout than BeatSaber.
> Additional public world with OpenFlight implemented

- Packages/com.mattshark.openflight/Runtime/data.json
Source: https://mikedabird.itch.io/mikevali
Wingtip length can be adjusted and the appropriate offset ranges from 3.5 to 7.5; 5.5 is equal to setting it to 50%.
> Add Mike'Vali by Mike Da Bird

- Packages/com.mattshark.openflight/Runtime/data.json
Link to base: https://morghus.gumroad.com/l/wyvernid
> [Avatar Addition] Wyvernid

- Packages/com.mattshark.openflight/Runtime/data.json
Paid:
* Ao by Miumu (https://store.vket.com/ja/items/7568)
* Hochumi by MOKURI project (https://store.vket.com/en/items/4128)
* Ragussiel by amati (https://am23ti.booth.pm/items/4472191)
* Runapaella by Aokuro (https://booth.pm/en/items/4917692)
* Sera/Replica by project_V.B.B (https://booth.pm/en/items/4020972)
* Torino by blo (https://blo.booth.pm/items/4889790)
Public Avatars:
* Iubati (SDK2) by Sparky42
* Iubati (SDK3) by Groxxy
* Nubatama Aratame by Nimono-oishi
> Several new bases

- Packages/com.mattshark.openflight/Runtime/data.json
https://bluegua.booth.pm/items/4988841
> Add Guavali

- Packages/com.mattshark.openflight/Runtime/data.json
Just wanted to add my custom version with the toggleable wings. Thanks :)
(on a side note: is it actually possible to toggle the flight capability based on whether the wings are turned on or not?)
> Added Toggleable Wings Krazen Nardo

- Packages/com.mattshark.openflight/Runtime/data.json
Picture of avatar:
https://media.discordapp.net/attachments/742349281998143519/1143845951870615572/VRChat_2023-08-23_21-47-29.792_1920x1080.png?width=736&height=413
> Adding Sear wyvern to data.json

- Packages/com.mattshark.openflight/Runtime/data.json
* Female Bat by Ximmer https://ximmer.gumroad.com/l/XimBat
* Feilong by FLASTORE https://booth.pm/ja/items/1903612
* Microbat by Neops https://neop.gumroad.com/l/vrcbat
* Toastacuga by Toastador
* Original https://drive.google.com/file/d/1k9P3Fy3rFoBkzYcqevjvIybxYyXl65Z6/view
* Updated https://drive.google.com/open?id=1ekIiFBnzJNhH2a6wwYLo2s5G-VuUlIY5
> Add Female Bat, Feilong, Microbat, Toastacuga

- Packages/com.mattshark.openflight/Runtime/data.json
Another avatar for the wing pile :)
> Add Darizard Custom Avatar

- Packages/com.mattshark.openflight/Runtime/data.json
* Necpho https://aokuro.booth.pm/items/5288991
* Rali'vala https://fluffrali.gumroad.com/l/Rali-valii
* Ayakaze Tsubame https://sunriseprisma.booth.pm/items/5281828
* Urabi https://kyubi.booth.pm/items/4736441
* Freje https://mochitig.booth.pm/items/3391581
* Bonjiri https://anaguraworks.booth.pm/items/2771327
* Sachi https://hernes.booth.pm/
> Add several avatars

- Packages/com.mattshark.openflight/Runtime/data.json
Added Floofvali on behalf of Da Floof (-Jinxy- in VRC) https://jinxyuwu.gumroad.com/
> Added Floofvali (prerelease)

- Packages/com.mattshark.openflight/Runtime/data.json
* Hoshi Avali (https://razedrake.gumroad.com/l/HoshiAvali)
> Add Hoshi Avali

- Packages/com.mattshark.openflight/Runtime/data.json
* https://therpgslayer.gumroad.com/l/Pawvali
> Added Paw'vali

- Packages/com.mattshark.openflight/Runtime/data.json
* Gala'vali - https://jupiturn.gumroad.com/l/Galavali
> Add Gala'vali

- Packages/com.mattshark.openflight/Runtime/data.json
I heavily modified the rig of the Hoshi Avali while fixing a lot of issues with it.
Here's the gumroad link: 
https://emberavali.gumroad.com/l/Hoshi
And the public version:
https://vrchat.com/home/avatar/avtr_e3a0d96d-40ff-412f-b4b8-86fefd710b61
> Adding my public edit of the Hoshi Avali

- Packages/com.mattshark.openflight/Runtime/data.json
avatar links: 
https://vodahminhahnu.gumroad.com/l/yacmh
https://bentobox.gumroad.com/l/BatVRC?&referrer=https%3A%2F%2Fwww.vrcarena.com
https://www.vrcarena.com/assets/f17f2-bat-vrchat-avatar-base
> [Avatar addition] skip4d bat, bento's vrchat bat, The unknown

- Packages/com.mattshark.openflight/Runtime/data.json
This is a private bird-type avatar by and for Eldarath and Nambroth
> [Avatar addition] Eld Phoenix

- Packages/com.mattshark.openflight/Runtime/data.json
- docs/ADDINGAVATARS.md
Added the Spiri'vali, and updated the doc to include committing the project to a fork file. Will update later to include making a pull request.
> [Avatar Addition] Spiri'vali

- Packages/com.mattshark.openflight/Runtime/data.json
Little Blackbird is a non-anthro bird with wings that can be toggled to arm puppets. You can see it here: https://booth.pm/en/items/5647662
Swooping around in this little cutie is pretty fun! But watch out he might steal your fried potato snacks!
> [Avatar Addition] Little Blackbird

- Packages/com.mattshark.openflight/Runtime/data.json
Hello!
Pull Request to add my Avali Spirit VRChat Avatar to the OpenFlight System.
- DarksSpirit019 aka -Dark-Spirit-
> Add Avali Spirit VRChat Avatar

- Packages/com.mattshark.openflight/Runtime/data.json
Ori'vali Base: https://mikedabird.itch.io/orivali
> [Avatar Addition] Ori'Vali

- Packages/com.mattshark.openflight/Runtime/data.json
Gumroad page: https://questingcrusader.gumroad.com/l/KAvali
> Added KAvali by Questing Crusader

- Packages/com.mattshark.openflight/Runtime/data.json
Adding hash data from demo version of AS.4VA-L1 by Aeyon Systems, still not sure I did the branching correctly but feel free to yell at me and i'll get this cleaned up asap, just like last time!
> [Avatar Addition] AS.4VA-L1

- Packages/com.mattshark.openflight/Runtime/data.json
https://rocrocot.gumroad.com/l/pteryxis
> [Avatar Addition] Pteryxis

- Packages/com.mattshark.openflight/Runtime/data.json
I changed their arm length a little bit to give them a different hash than the regular tigerbee.
> [Avatar Addition] Purpzbee

- Packages/com.mattshark.openflight/Runtime/data.json
Thought I might've accidentally changed something on my personal upload, but found the [public upload](https://vrchat.com/home/avatar/avtr_89c38379-bd1b-480e-8467-a322352b395f) to not be detected either (and hashing the same as my own), so: Here it is!
Checked hashes in both:
- https://vrchat.com/home/world/wrld_ef75dcc8-02fa-43ef-8f42-7b8159783d3d and
- https://vrchat.com/home/world/wrld_9de0ee57-813f-416d-8b84-b41c4c259de1
'cause paranoia, or something.
> [Avatar Addition] ZWyvern V2

- Packages/com.mattshark.openflight/Runtime/data.json
> [Avatar Addition] Mantled Vern

- Packages/com.mattshark.openflight/Runtime/data.json
Might need to change the name of the avatar to Av-Eli not base Av-Eli. only had that on there for testing.
> [Avatar Addition] Av-Eli

- Packages/com.mattshark.openflight/Runtime/data.json
https://vrchat.com/home/launch?worldId=wrld_a4db8b13-d0b3-4653-abcd-6345a876cec6&instanceId=51385~private(usr_8f11ddd5-aeb3-4706-970f-b147a095e8d6)~region(us)~nonce(b71bf025-bb7f-4504-8018-82c81d08c775)
> [Avatar Addition] Batdal v2 Hash

- Packages/com.mattshark.openflight/Runtime/data.json
> [Avatar Addition] SAM (Sap Avali Model)

- Packages/com.mattshark.openflight/Runtime/data.json
note: the avatar arms are really weird, this should be the best offset
> [Avatar Addition] Uncia Gryphonet

- Packages/com.mattshark.openflight/Runtime/data.json
Adding Support for the Durgarra and Wyvernarra VRChat Avatars. Both can be found on the same Gumroad Page: https://kyderra.gumroad.com/l/Urawr?layout=profile
> ADD: Durgarra and Wyvernarra

- Packages/com.mattshark.openflight/Runtime/data.json
The image for the avatar for the repository!
> [Avatar Addition] Litria

- Packages/com.mattshark.openflight/Runtime/data.json
I'm the pink one! pretty much just a reproportioned Spiri'vali <3
May I please fly? 👉👈
> [Avatar Addition] PhoenixFallen Mini'spiri'vali

- Packages/com.mattshark.openflight/Runtime/data.json
https://jinxyuwu.gumroad.com/l/floofvali
> Add Floofvali v1.2

- Packages/com.mattshark.openflight/Runtime/data.json
> [Avatar Addition] Batty Bat

- Packages/com.mattshark.openflight/Runtime/data.json
https://boosty.to/corvidcurse/posts/bb498ad9-ca7b-45dc-a8fd-83ae3961d674
> [Avatar Addition] Dromeowyrm v2

- Packages/com.mattshark.openflight/Runtime/data.json
https://tokyozilla.gumroad.com/l/NeosWelpling
> adding welpling

- Packages/com.mattshark.openflight/Runtime/data.json
https://ko-fi.com/s/308d0bb04a
> [Avatar Addition] CORVID'S CORVID

- Packages/com.mattshark.openflight/Runtime/data.json
https://jinxxy.com/BurnsToShine/stellaura
> [Avatar Addition] Stellaura

- Packages/com.mattshark.openflight/Runtime/data.json
https://avislime.gumroad.com/l/taWpg (Lunar Kyliin v2)
https://avislime.gumroad.com/l/kyliin2 (Solar Kyliin v2)
> [Avatar Addition] Kyliin v2

- Packages/com.mattshark.openflight/Runtime/data.json
> Added Personal Jerry Base

- Packages/com.mattshark.openflight/Runtime/data.json
From the commit, which didn't propagate here:
Add PROTOVALI
https://jinxyuwu.gumroad.com/l/protovali
Creator now uses ItsFloofy; updated their old entries (-Jinxy- and Da Floof)
> Add PROTOVALI

- Packages/com.mattshark.openflight/Runtime/data.json
Added support for the v4 of the Nexa'vali.
Added Nexa'vali model variant.
> Updated Nexa'vali Hash for v4 and add a model variant.

- Packages/com.mattshark.openflight/Runtime/data.json
Changed their username from Neszumi to Luna Neszy
> Neszumi username update

- Packages/com.mattshark.openflight/Runtime/data.json
New avali avatar base created by Haggets https://haggets.gumroad.com/l/haggitavali
> [Avatar Addition] Haggitavali #144

- Packages/com.mattshark.openflight/Runtime/data.json
A snow owl I kitbashed a Lambie, a Noix, and a Milnenu. Here's a picture of said owl
> [Avatar Addition] Snow Owl

- Packages/com.mattshark.openflight/Runtime/data.json
Derp Butt Birb is a port of an avatar from Second Life
Mieze Jerry Avali is my edit of the Jerry Avali
> [Avatar Addition] Derp Butt Birb and Mieze Jerry Avali edit

- Packages/com.mattshark.openflight/Runtime/data.json
Modified Corvid's Corvid in which it seems I moved the head bone slightly when adding first-person beak business, and so changed the hash: https://vrchat.com/home/avatar/avtr_d068b19a-ca79-4fdc-8468-45337eda6d20
> [Avatar Addition] Modified Corvid's Corvid

- Packages/com.mattshark.openflight/Runtime/data.json
Avatar to be released in a couple days. PR for @astone595
> Add Revali

- Packages/com.mattshark.openflight/Runtime/data.json
Avatar Base Name : Apheli`vali
Avatar Creator : AComfyPillow
Introducer : Dream_LP
Link: https://acomfypillow.gumroad.com/l/Aphelivali
> [Avatar Addition] Apheli`vali

- Packages/com.mattshark.openflight/Runtime/data.json
adding my avatar base, planning on releasing on 2025-07-08
i can provide pictures if you need, i think you've already seen them in discord though
> [Avatar Addition] Ele'vali

- Packages/com.mattshark.openflight/Runtime/data.json
https://featherpile.awawi.nexus/talivali/
> [Avatar Addition] TaliVali

- Packages/com.mattshark.openflight/Runtime/data.json
https://ko-fi.com/s/3f24fea9bf
> [Avatar Addition] Phovali

- Packages/com.mattshark.openflight/Runtime/data.json
https://toastysheeb.gumroad.com/l/AvaliPooltoy?layout=profile&recommended_by=library
> [Avatar Addition] Avali Pooltoy

- Packages/com.mattshark.openflight/Runtime/data.json
https://www.artbyneffertity.com/store/dovabrodian
Added base version of Dovabrodian.
> [Avatar Addition] Dovabrodian
